version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DBHOST=localhost
      - POSTGRES_DB=api_music_app_development
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgres/data"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data

  web: 
    build: .
    image: rails-docker
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  dbdata:
