---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: Check if the server is alive
      responses:
        '200':
          description: Server is alive
  "/sign_in":
    post:
      summary: Creates a session
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable_entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  "/sign_out":
    delete:
      summary: Destroy a session
      security:
      - Bearer: []
      parameters:
      - name: refresh_token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/sign_up":
    post:
      summary: Creates a new user
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - username
              - email
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
