# name: CI

# on:
#   - push
#   - pull_request

# jobs:
#   test:
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest]
#         ruby: 
#           - 3.2.2
#     runs-on: ${{ matrix.os }}
#     steps: 
#       - name: Set action checkout
#         uses: actions/checkout@v4.1.0
#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1.156.0
#         with:
#           ruby-version: ${{ matrix.ruby }}
#           bundler-cache: true
#       - name: Run Rubocop
#         run: bundle exec rubocop
#       - name: Run Rspec
#         run: bundle exec rspec

name: CI
on:
  - push
  - pull_request

jobs:
  install-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4.1.0
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.156.0
        with:
          bundler-cache: true
  test:
    runs-on: ubuntu-latest
    needs: install-cache
    timeout-minutes: 10
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4.1.0
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.156.0
        with:
          bundler-cache: true
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/api_music_app_test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          rails db:create
          rails db:schema:load
          bundle exec rspec
      - name: Smoke test database seeds
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/myapp_test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rails db:reset