name: CI

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: 
          - 3.2.2
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Set action checkout
        uses: actions/checkout@v4.1.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.156.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rubocop
        uses: bundle exec rubocop
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage
          path: coverage/index.html
       


